set_property SRC_FILE_INFO {cfile:/home/subhagato/Codes/marie_smart/marie_smart.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc rfile:../../../marie_smart.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc id:1 order:EARLY scoped_inst:design_1_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/subhagato/Codes/smartheadlight_fpga/CameraLinkTest_only_dw_converter/CameraLinkTest.srcs/sources_1/bd/design_1/Cameralink_deca.xdc rfile:../../../../smartheadlight_fpga/CameraLinkTest_only_dw_converter/CameraLinkTest.srcs/sources_1/bd/design_1/Cameralink_deca.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/subhagato/Codes/marie_smart/marie_smart.srcs/sources_1/bd/design_1/ip/design_1_cameralink_to_axis_0_0/ip/v_vid_in_axi4s_0/v_vid_in_axi4s_0_clocks.xdc rfile:../../../marie_smart.srcs/sources_1/bd/design_1/ip/design_1_cameralink_to_axis_0_0/ip/v_vid_in_axi4s_0/v_vid_in_axi4s_0_clocks.xdc id:3 order:LATE scoped_inst:design_1_i/cameralink_to_axis_0/inst/v_vid_in_axi4s_0_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/subhagato/Codes/marie_smart/marie_smart.srcs/sources_1/bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0_clocks.xdc rfile:../../../marie_smart.srcs/sources_1/bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0_clocks.xdc id:4 order:LATE scoped_inst:design_1_i/v_axi4s_vid_out_0/inst} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.05
set_property src_info {type:XDC file:2 line:501 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:507 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:510 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:511 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/cameralink_to_axis_0/inst/clk_out]]
set_property src_info {type:XDC file:2 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:513 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list design_1_i/axis_dwidth_converter_0/m_axis_tready]]
set_property src_info {type:XDC file:2 line:514 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:2 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:522 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:2 line:524 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list design_1_i/clk_wiz_0/inst/clkfbout_buf_design_1_clk_wiz_0_0]]
set_property src_info {type:XDC file:2 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:2 line:526 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list design_1_i/v_axi4s_vid_out_0/vid_io_out_ce]]
set_property src_info {type:XDC file:2 line:527 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_2 ila
set_property src_info {type:XDC file:2 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:530 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:534 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
set_property src_info {type:XDC file:2 line:537 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/clk [get_nets [list design_1_i/clk_wiz_0_clk_out2]]
set_property src_info {type:XDC file:2 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:2 line:539 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe0 [get_nets [list {design_1_i/v_axi4s_vid_out_0/vid_data[0]} {design_1_i/v_axi4s_vid_out_0/vid_data[1]} {design_1_i/v_axi4s_vid_out_0/vid_data[2]} {design_1_i/v_axi4s_vid_out_0/vid_data[3]} {design_1_i/v_axi4s_vid_out_0/vid_data[4]} {design_1_i/v_axi4s_vid_out_0/vid_data[5]} {design_1_i/v_axi4s_vid_out_0/vid_data[6]} {design_1_i/v_axi4s_vid_out_0/vid_data[7]} {design_1_i/v_axi4s_vid_out_0/vid_data[8]} {design_1_i/v_axi4s_vid_out_0/vid_data[9]} {design_1_i/v_axi4s_vid_out_0/vid_data[10]} {design_1_i/v_axi4s_vid_out_0/vid_data[11]} {design_1_i/v_axi4s_vid_out_0/vid_data[12]} {design_1_i/v_axi4s_vid_out_0/vid_data[13]} {design_1_i/v_axi4s_vid_out_0/vid_data[14]} {design_1_i/v_axi4s_vid_out_0/vid_data[15]}]]
set_property src_info {type:XDC file:2 line:540 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_3 ila
set_property src_info {type:XDC file:2 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:2 line:542 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:2 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:2 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:2 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:2 line:546 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:2 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:2 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_3]
set_property src_info {type:XDC file:2 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/clk]
set_property src_info {type:XDC file:2 line:550 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/clk [get_nets [list design_1_i/clk_wiz_0_clk_out1]]
set_property src_info {type:XDC file:2 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_3/probe0]
set_property src_info {type:XDC file:2 line:552 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe0 [get_nets [list {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[0]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[1]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[2]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[3]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[4]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[5]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[6]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[7]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[8]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[9]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[10]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[11]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[12]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[13]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[14]} {design_1_i/v_axi4s_vid_out_0/s_axis_video_tdata[15]}]]
set_property src_info {type:XDC file:2 line:553 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:554 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:555 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list design_1_i/hls_cropping_vert_strm_0/src_V_V_TREADY]]
set_property src_info {type:XDC file:2 line:556 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:558 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/hls_cropping_vert_strm_0/src_V_V_TVALID]]
set_property src_info {type:XDC file:2 line:559 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:560 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe1]
set_property src_info {type:XDC file:2 line:561 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe1 [get_nets [list design_1_i/v_axi4s_vid_out_0/locked]]
set_property src_info {type:XDC file:2 line:562 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe2]
set_property src_info {type:XDC file:2 line:564 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe2 [get_nets [list design_1_i/v_axi4s_vid_out_0/rst]]
set_property src_info {type:XDC file:2 line:565 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:566 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe3]
set_property src_info {type:XDC file:2 line:567 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe3 [get_nets [list design_1_i/v_axi4s_vid_out_0/vid_active_video]]
set_property src_info {type:XDC file:2 line:568 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe4]
set_property src_info {type:XDC file:2 line:570 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe4 [get_nets [list design_1_i/v_axi4s_vid_out_0/vid_field_id]]
set_property src_info {type:XDC file:2 line:571 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe5]
set_property src_info {type:XDC file:2 line:573 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe5 [get_nets [list design_1_i/v_axi4s_vid_out_0/vid_hblank]]
set_property src_info {type:XDC file:2 line:574 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:575 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe6]
set_property src_info {type:XDC file:2 line:576 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe6 [get_nets [list design_1_i/v_axi4s_vid_out_0/vid_hsync]]
set_property src_info {type:XDC file:2 line:577 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:578 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe7]
set_property src_info {type:XDC file:2 line:579 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe7 [get_nets [list design_1_i/v_axi4s_vid_out_0/vid_vblank]]
set_property src_info {type:XDC file:2 line:580 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe8]
set_property src_info {type:XDC file:2 line:582 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe8 [get_nets [list design_1_i/v_axi4s_vid_out_0/vid_vsync]]
set_property src_info {type:XDC file:2 line:583 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:584 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe9]
set_property src_info {type:XDC file:2 line:585 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe9 [get_nets [list design_1_i/v_axi4s_vid_out_0/vtg_active_video]]
set_property src_info {type:XDC file:2 line:586 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:587 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe10]
set_property src_info {type:XDC file:2 line:588 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe10 [get_nets [list design_1_i/v_axi4s_vid_out_0/vtg_ce]]
set_property src_info {type:XDC file:2 line:589 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:590 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe11]
set_property src_info {type:XDC file:2 line:591 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe11 [get_nets [list design_1_i/v_axi4s_vid_out_0/vtg_hblank]]
set_property src_info {type:XDC file:2 line:592 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe12]
set_property src_info {type:XDC file:2 line:594 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe12 [get_nets [list design_1_i/v_axi4s_vid_out_0/vtg_hsync]]
set_property src_info {type:XDC file:2 line:595 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:596 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe13]
set_property src_info {type:XDC file:2 line:597 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe13 [get_nets [list design_1_i/v_axi4s_vid_out_0/vtg_vblank]]
set_property src_info {type:XDC file:2 line:598 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:599 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe14]
set_property src_info {type:XDC file:2 line:600 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe14 [get_nets [list design_1_i/v_axi4s_vid_out_0/vtg_vsync]]
set_property src_info {type:XDC file:2 line:601 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:602 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_3/probe1]
set_property src_info {type:XDC file:2 line:603 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe1 [get_nets [list {design_1_i/axis_dwidth_converter_0/s_axis_tuser[0]} {design_1_i/axis_dwidth_converter_0/s_axis_tuser[1]} {design_1_i/axis_dwidth_converter_0/s_axis_tuser[2]} {design_1_i/axis_dwidth_converter_0/s_axis_tuser[3]} {design_1_i/axis_dwidth_converter_0/s_axis_tuser[4]} {design_1_i/axis_dwidth_converter_0/s_axis_tuser[5]} {design_1_i/axis_dwidth_converter_0/s_axis_tuser[6]} {design_1_i/axis_dwidth_converter_0/s_axis_tuser[7]} {design_1_i/axis_dwidth_converter_0/s_axis_tuser[8]} {design_1_i/axis_dwidth_converter_0/s_axis_tuser[9]}]]
set_property src_info {type:XDC file:2 line:604 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 80 [get_debug_ports u_ila_3/probe2]
set_property src_info {type:XDC file:2 line:606 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe2 [get_nets [list {design_1_i/axis_dwidth_converter_0/s_axis_tdata[0]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[1]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[2]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[3]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[4]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[5]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[6]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[7]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[8]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[9]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[10]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[11]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[12]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[13]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[14]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[15]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[16]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[17]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[18]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[19]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[20]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[21]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[22]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[23]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[24]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[25]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[26]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[27]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[28]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[29]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[30]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[31]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[32]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[33]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[34]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[35]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[36]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[37]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[38]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[39]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[40]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[41]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[42]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[43]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[44]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[45]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[46]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[47]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[48]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[49]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[50]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[51]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[52]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[53]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[54]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[55]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[56]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[57]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[58]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[59]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[60]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[61]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[62]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[63]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[64]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[65]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[66]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[67]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[68]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[69]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[70]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[71]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[72]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[73]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[74]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[75]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[76]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[77]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[78]} {design_1_i/axis_dwidth_converter_0/s_axis_tdata[79]}]]
set_property src_info {type:XDC file:2 line:607 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:608 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_3/probe3]
set_property src_info {type:XDC file:2 line:609 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe3 [get_nets [list {design_1_i/axis_dwidth_converter_0/m_axis_tuser[0]} {design_1_i/axis_dwidth_converter_0/m_axis_tuser[1]} {design_1_i/axis_dwidth_converter_0/m_axis_tuser[2]} {design_1_i/axis_dwidth_converter_0/m_axis_tuser[3]} {design_1_i/axis_dwidth_converter_0/m_axis_tuser[4]} {design_1_i/axis_dwidth_converter_0/m_axis_tuser[5]} {design_1_i/axis_dwidth_converter_0/m_axis_tuser[6]} {design_1_i/axis_dwidth_converter_0/m_axis_tuser[7]}]]
set_property src_info {type:XDC file:2 line:610 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:611 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe4]
set_property src_info {type:XDC file:2 line:612 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe4 [get_nets [list {design_1_i/hls_cropping_vert_strm_0/src_valid_V[0]}]]
set_property src_info {type:XDC file:2 line:613 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:614 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe5]
set_property src_info {type:XDC file:2 line:615 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe5 [get_nets [list {design_1_i/hls_cropping_vert_strm_0/eol_dst_V[0]}]]
set_property src_info {type:XDC file:2 line:616 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe6]
set_property src_info {type:XDC file:2 line:618 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe6 [get_nets [list {design_1_i/hls_cropping_vert_strm_0/sof_src_V[0]}]]
set_property src_info {type:XDC file:2 line:619 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:620 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe7]
set_property src_info {type:XDC file:2 line:621 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe7 [get_nets [list {design_1_i/hls_cropping_vert_strm_0/sof_dst_V[0]}]]
set_property src_info {type:XDC file:2 line:622 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:623 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_3/probe8]
set_property src_info {type:XDC file:2 line:624 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe8 [get_nets [list {design_1_i/hls_cropping_vert_strm_0/dst_V[0]} {design_1_i/hls_cropping_vert_strm_0/dst_V[1]} {design_1_i/hls_cropping_vert_strm_0/dst_V[2]} {design_1_i/hls_cropping_vert_strm_0/dst_V[3]} {design_1_i/hls_cropping_vert_strm_0/dst_V[4]} {design_1_i/hls_cropping_vert_strm_0/dst_V[5]} {design_1_i/hls_cropping_vert_strm_0/dst_V[6]} {design_1_i/hls_cropping_vert_strm_0/dst_V[7]} {design_1_i/hls_cropping_vert_strm_0/dst_V[8]} {design_1_i/hls_cropping_vert_strm_0/dst_V[9]} {design_1_i/hls_cropping_vert_strm_0/dst_V[10]} {design_1_i/hls_cropping_vert_strm_0/dst_V[11]} {design_1_i/hls_cropping_vert_strm_0/dst_V[12]} {design_1_i/hls_cropping_vert_strm_0/dst_V[13]} {design_1_i/hls_cropping_vert_strm_0/dst_V[14]} {design_1_i/hls_cropping_vert_strm_0/dst_V[15]}]]
set_property src_info {type:XDC file:2 line:625 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:626 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_3/probe9]
set_property src_info {type:XDC file:2 line:627 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe9 [get_nets [list {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[0]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[1]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[2]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[3]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[4]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[5]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[6]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[7]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[8]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[9]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[10]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[11]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[12]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[13]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[14]} {design_1_i/hls_cropping_vert_strm_0/src_V_V_TDATA[15]}]]
set_property src_info {type:XDC file:2 line:628 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:629 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe10]
set_property src_info {type:XDC file:2 line:630 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe10 [get_nets [list {design_1_i/hls_cropping_vert_strm_0/dst_valid_dst_V[0]}]]
set_property src_info {type:XDC file:2 line:631 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:632 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_3/probe11]
set_property src_info {type:XDC file:2 line:633 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe11 [get_nets [list {design_1_i/axis_dwidth_converter_0/m_axis_tkeep[0]} {design_1_i/axis_dwidth_converter_0/m_axis_tkeep[1]} {design_1_i/axis_dwidth_converter_0/m_axis_tkeep[2]} {design_1_i/axis_dwidth_converter_0/m_axis_tkeep[3]} {design_1_i/axis_dwidth_converter_0/m_axis_tkeep[4]} {design_1_i/axis_dwidth_converter_0/m_axis_tkeep[5]} {design_1_i/axis_dwidth_converter_0/m_axis_tkeep[6]} {design_1_i/axis_dwidth_converter_0/m_axis_tkeep[7]}]]
set_property src_info {type:XDC file:2 line:634 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_3/probe12]
set_property src_info {type:XDC file:2 line:636 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe12 [get_nets [list {design_1_i/axis_dwidth_converter_0/m_axis_tdata[0]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[1]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[2]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[3]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[4]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[5]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[6]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[7]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[8]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[9]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[10]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[11]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[12]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[13]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[14]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[15]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[16]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[17]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[18]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[19]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[20]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[21]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[22]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[23]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[24]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[25]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[26]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[27]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[28]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[29]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[30]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[31]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[32]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[33]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[34]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[35]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[36]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[37]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[38]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[39]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[40]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[41]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[42]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[43]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[44]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[45]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[46]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[47]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[48]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[49]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[50]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[51]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[52]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[53]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[54]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[55]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[56]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[57]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[58]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[59]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[60]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[61]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[62]} {design_1_i/axis_dwidth_converter_0/m_axis_tdata[63]}]]
set_property src_info {type:XDC file:2 line:637 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:638 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe13]
set_property src_info {type:XDC file:2 line:639 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe13 [get_nets [list design_1_i/axis_dwidth_converter_0/m_axis_tlast]]
set_property src_info {type:XDC file:2 line:640 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe14]
set_property src_info {type:XDC file:2 line:642 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe14 [get_nets [list design_1_i/axis_dwidth_converter_0/m_axis_tvalid]]
set_property src_info {type:XDC file:2 line:643 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:644 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe15]
set_property src_info {type:XDC file:2 line:645 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe15 [get_nets [list design_1_i/axis_dwidth_converter_0/s_axis_tlast]]
set_property src_info {type:XDC file:2 line:646 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:647 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe16]
set_property src_info {type:XDC file:2 line:648 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe16 [get_nets [list design_1_i/axis_dwidth_converter_0/s_axis_tready]]
set_property src_info {type:XDC file:2 line:649 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:650 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe17]
set_property src_info {type:XDC file:2 line:651 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe17 [get_nets [list design_1_i/axis_dwidth_converter_0/s_axis_tvalid]]
set_property src_info {type:XDC file:2 line:652 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe18]
set_property src_info {type:XDC file:2 line:654 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe18 [get_nets [list design_1_i/v_axi4s_vid_out_0/s_axis_video_tlast]]
set_property src_info {type:XDC file:2 line:655 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:656 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe19]
set_property src_info {type:XDC file:2 line:657 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe19 [get_nets [list design_1_i/v_axi4s_vid_out_0/s_axis_video_tready]]
set_property src_info {type:XDC file:2 line:658 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:659 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe20]
set_property src_info {type:XDC file:2 line:660 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe20 [get_nets [list design_1_i/v_axi4s_vid_out_0/s_axis_video_tuser]]
set_property src_info {type:XDC file:2 line:661 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:662 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe21]
set_property src_info {type:XDC file:2 line:663 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe21 [get_nets [list design_1_i/v_axi4s_vid_out_0/s_axis_video_tvalid]]
set_property src_info {type:XDC file:2 line:664 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_3 probe
set_property src_info {type:XDC file:2 line:665 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_3/probe22]
set_property src_info {type:XDC file:2 line:666 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_3/probe22 [get_nets [list design_1_i/v_axi4s_vid_out_0/wr_error]]
set_property src_info {type:XDC file:2 line:670 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:671 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:672 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:673 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out]
set_property src_info {type:SCOPED_XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins design_1_i/cameralink_to_axis_0/inst/v_vid_in_axi4s_0_inst/inst/vid_io_in_clk]] -to [all_registers -clock [get_clocks -of_objects [get_pins design_1_i/cameralink_to_axis_0/inst/v_vid_in_axi4s_0_inst/inst/aclk]]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/cameralink_to_axis_0/inst/v_vid_in_axi4s_0_inst/inst/vid_io_in_clk]]]
set_property src_info {type:SCOPED_XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins design_1_i/cameralink_to_axis_0/inst/v_vid_in_axi4s_0_inst/inst/aclk]] -to [all_registers -clock [get_clocks -of_objects [get_pins design_1_i/cameralink_to_axis_0/inst/v_vid_in_axi4s_0_inst/inst/vid_io_in_clk]]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/cameralink_to_axis_0/inst/v_vid_in_axi4s_0_inst/inst/aclk]]]
set_property src_info {type:SCOPED_XDC file:4 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins design_1_i/v_axi4s_vid_out_0/inst/vid_io_out_clk]] -to [all_registers -clock [get_clocks -of_objects [get_pins design_1_i/v_axi4s_vid_out_0/inst/aclk]]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/v_axi4s_vid_out_0/inst/vid_io_out_clk]]]
set_property src_info {type:SCOPED_XDC file:4 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins design_1_i/v_axi4s_vid_out_0/inst/aclk]] -to [all_registers -clock [get_clocks -of_objects [get_pins design_1_i/v_axi4s_vid_out_0/inst/vid_io_out_clk]]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins design_1_i/v_axi4s_vid_out_0/inst/aclk]]]
