// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_cropping_strm,hls_ip_2014_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=15.182000,HLS_SYN_LAT=191,HLS_SYN_TPT=192,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6115,HLS_SYN_LUT=4430}" *)

module hls_cropping_strm (
        src_TDATA,
        src_TKEEP,
        src_TSTRB,
        src_TUSER,
        src_TLAST,
        src_TID,
        src_TDEST,
        dst_V_V_TDATA,
        dst_valid,
        sof_sig,
        ap_clk,
        ap_rst_n,
        src_TVALID,
        src_TREADY,
        dst_V_V_TVALID,
        dst_V_V_TREADY,
        sof_sig_ap_vld,
        dst_valid_ap_vld
);

parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_true = 1'b1;

input  [7:0] src_TDATA;
input  [0:0] src_TKEEP;
input  [0:0] src_TSTRB;
input  [0:0] src_TUSER;
input  [0:0] src_TLAST;
input  [0:0] src_TID;
input  [0:0] src_TDEST;
output  [15:0] dst_V_V_TDATA;
output   dst_valid;
output   sof_sig;
input   ap_clk;
input   ap_rst_n;
input   src_TVALID;
output   src_TREADY;
output   dst_V_V_TVALID;
input   dst_V_V_TREADY;
output   sof_sig_ap_vld;
output   dst_valid_ap_vld;

reg    ap_rst_n_inv;
wire    hls_cropping_strm_Block_proc_U0_ap_start;
wire    hls_cropping_strm_Block_proc_U0_ap_done;
wire    hls_cropping_strm_Block_proc_U0_ap_continue;
wire    hls_cropping_strm_Block_proc_U0_ap_idle;
wire    hls_cropping_strm_Block_proc_U0_ap_ready;
wire   [7:0] hls_cropping_strm_Block_proc_U0_src_TDATA;
wire    hls_cropping_strm_Block_proc_U0_src_TVALID;
wire    hls_cropping_strm_Block_proc_U0_src_TREADY;
wire   [0:0] hls_cropping_strm_Block_proc_U0_src_TKEEP;
wire   [0:0] hls_cropping_strm_Block_proc_U0_src_TSTRB;
wire   [0:0] hls_cropping_strm_Block_proc_U0_src_TUSER;
wire   [0:0] hls_cropping_strm_Block_proc_U0_src_TLAST;
wire   [0:0] hls_cropping_strm_Block_proc_U0_src_TID;
wire   [0:0] hls_cropping_strm_Block_proc_U0_src_TDEST;
wire   [15:0] hls_cropping_strm_Block_proc_U0_dst_V_V_TDATA;
wire    hls_cropping_strm_Block_proc_U0_dst_V_V_TVALID;
wire    hls_cropping_strm_Block_proc_U0_dst_V_V_TREADY;
wire   [0:0] hls_cropping_strm_Block_proc_U0_sof_sig;
wire    hls_cropping_strm_Block_proc_U0_sof_sig_ap_vld;
wire   [0:0] hls_cropping_strm_Block_proc_U0_dst_valid;
wire    hls_cropping_strm_Block_proc_U0_dst_valid_ap_vld;
wire    ap_sig_hs_continue;
reg    ap_CS;
reg    ap_sig_hs_done;


hls_cropping_strm_Block_proc hls_cropping_strm_Block_proc_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( hls_cropping_strm_Block_proc_U0_ap_start ),
    .ap_done( hls_cropping_strm_Block_proc_U0_ap_done ),
    .ap_continue( hls_cropping_strm_Block_proc_U0_ap_continue ),
    .ap_idle( hls_cropping_strm_Block_proc_U0_ap_idle ),
    .ap_ready( hls_cropping_strm_Block_proc_U0_ap_ready ),
    .src_TDATA( hls_cropping_strm_Block_proc_U0_src_TDATA ),
    .src_TVALID( hls_cropping_strm_Block_proc_U0_src_TVALID ),
    .src_TREADY( hls_cropping_strm_Block_proc_U0_src_TREADY ),
    .src_TKEEP( hls_cropping_strm_Block_proc_U0_src_TKEEP ),
    .src_TSTRB( hls_cropping_strm_Block_proc_U0_src_TSTRB ),
    .src_TUSER( hls_cropping_strm_Block_proc_U0_src_TUSER ),
    .src_TLAST( hls_cropping_strm_Block_proc_U0_src_TLAST ),
    .src_TID( hls_cropping_strm_Block_proc_U0_src_TID ),
    .src_TDEST( hls_cropping_strm_Block_proc_U0_src_TDEST ),
    .dst_V_V_TDATA( hls_cropping_strm_Block_proc_U0_dst_V_V_TDATA ),
    .dst_V_V_TVALID( hls_cropping_strm_Block_proc_U0_dst_V_V_TVALID ),
    .dst_V_V_TREADY( hls_cropping_strm_Block_proc_U0_dst_V_V_TREADY ),
    .sof_sig( hls_cropping_strm_Block_proc_U0_sof_sig ),
    .sof_sig_ap_vld( hls_cropping_strm_Block_proc_U0_sof_sig_ap_vld ),
    .dst_valid( hls_cropping_strm_Block_proc_U0_dst_valid ),
    .dst_valid_ap_vld( hls_cropping_strm_Block_proc_U0_dst_valid_ap_vld )
);



/// assign process. ///
always @(posedge ap_clk)
begin
    ap_CS <= ap_const_logic_0;
end

/// ap_sig_hs_done assign process. ///
always @ (hls_cropping_strm_Block_proc_U0_ap_done)
begin
    if ((hls_cropping_strm_Block_proc_U0_ap_done == ap_const_logic_1)) begin
        ap_sig_hs_done = ap_const_logic_1;
    end else begin
        ap_sig_hs_done = ap_const_logic_0;
    end
end

/// ap_rst_n_inv assign process. ///
always @ (ap_rst_n)
begin
    ap_rst_n_inv = ~ap_rst_n;
end
assign ap_sig_hs_continue = ap_const_logic_0;
assign dst_V_V_TDATA = hls_cropping_strm_Block_proc_U0_dst_V_V_TDATA;
assign dst_V_V_TVALID = hls_cropping_strm_Block_proc_U0_dst_V_V_TVALID;
assign dst_valid = hls_cropping_strm_Block_proc_U0_dst_valid;
assign dst_valid_ap_vld = hls_cropping_strm_Block_proc_U0_dst_valid_ap_vld;
assign hls_cropping_strm_Block_proc_U0_ap_continue = ap_const_logic_1;
assign hls_cropping_strm_Block_proc_U0_ap_start = ap_const_logic_1;
assign hls_cropping_strm_Block_proc_U0_dst_V_V_TREADY = dst_V_V_TREADY;
assign hls_cropping_strm_Block_proc_U0_src_TDATA = src_TDATA;
assign hls_cropping_strm_Block_proc_U0_src_TDEST = src_TDEST;
assign hls_cropping_strm_Block_proc_U0_src_TID = src_TID;
assign hls_cropping_strm_Block_proc_U0_src_TKEEP = src_TKEEP;
assign hls_cropping_strm_Block_proc_U0_src_TLAST = src_TLAST;
assign hls_cropping_strm_Block_proc_U0_src_TSTRB = src_TSTRB;
assign hls_cropping_strm_Block_proc_U0_src_TUSER = src_TUSER;
assign hls_cropping_strm_Block_proc_U0_src_TVALID = src_TVALID;
assign sof_sig = hls_cropping_strm_Block_proc_U0_sof_sig;
assign sof_sig_ap_vld = hls_cropping_strm_Block_proc_U0_sof_sig_ap_vld;
assign src_TREADY = hls_cropping_strm_Block_proc_U0_src_TREADY;


endmodule //hls_cropping_strm

