// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_threshold,hls_ip_2014_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=1.998000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4,HLS_SYN_LUT=66}" *)

module hls_threshold (
        src_TDATA,
        src_TKEEP,
        src_TSTRB,
        src_TUSER,
        src_TLAST,
        src_TID,
        src_TDEST,
        dst_TDATA,
        dst_TKEEP,
        dst_TSTRB,
        dst_TUSER,
        dst_TLAST,
        dst_TID,
        dst_TDEST,
        ap_clk,
        ap_rst_n,
        src_TVALID,
        src_TREADY,
        dst_TVALID,
        dst_TREADY
);

parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_true = 1'b1;
parameter    ap_const_logic_0 = 1'b0;

input  [63:0] src_TDATA;
input  [7:0] src_TKEEP;
input  [7:0] src_TSTRB;
input  [0:0] src_TUSER;
input  [0:0] src_TLAST;
input  [0:0] src_TID;
input  [0:0] src_TDEST;
output  [7:0] dst_TDATA;
output  [0:0] dst_TKEEP;
output  [0:0] dst_TSTRB;
output  [0:0] dst_TUSER;
output  [0:0] dst_TLAST;
output  [0:0] dst_TID;
output  [0:0] dst_TDEST;
input   ap_clk;
input   ap_rst_n;
input   src_TVALID;
output   src_TREADY;
output   dst_TVALID;
input   dst_TREADY;

reg    ap_rst_n_inv;
wire    hls_threshold_Block_crit_edge_i_06_proc_U0_ap_start;
wire    hls_threshold_Block_crit_edge_i_06_proc_U0_ap_done;
wire    hls_threshold_Block_crit_edge_i_06_proc_U0_ap_continue;
wire    hls_threshold_Block_crit_edge_i_06_proc_U0_ap_idle;
wire    hls_threshold_Block_crit_edge_i_06_proc_U0_ap_ready;
wire   [63:0] hls_threshold_Block_crit_edge_i_06_proc_U0_src_TDATA;
wire    hls_threshold_Block_crit_edge_i_06_proc_U0_src_TVALID;
wire    hls_threshold_Block_crit_edge_i_06_proc_U0_src_TREADY;
wire   [7:0] hls_threshold_Block_crit_edge_i_06_proc_U0_src_TKEEP;
wire   [7:0] hls_threshold_Block_crit_edge_i_06_proc_U0_src_TSTRB;
wire   [0:0] hls_threshold_Block_crit_edge_i_06_proc_U0_src_TUSER;
wire   [0:0] hls_threshold_Block_crit_edge_i_06_proc_U0_src_TLAST;
wire   [0:0] hls_threshold_Block_crit_edge_i_06_proc_U0_src_TID;
wire   [0:0] hls_threshold_Block_crit_edge_i_06_proc_U0_src_TDEST;
wire   [7:0] hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TDATA;
wire    hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TVALID;
wire    hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TREADY;
wire   [0:0] hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TKEEP;
wire   [0:0] hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TSTRB;
wire   [0:0] hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TUSER;
wire   [0:0] hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TLAST;
wire   [0:0] hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TID;
wire   [0:0] hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TDEST;
wire    ap_sig_hs_continue;
reg    ap_CS;
reg    ap_sig_hs_done;


hls_threshold_Block_crit_edge_i_06_proc hls_threshold_Block_crit_edge_i_06_proc_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( hls_threshold_Block_crit_edge_i_06_proc_U0_ap_start ),
    .ap_done( hls_threshold_Block_crit_edge_i_06_proc_U0_ap_done ),
    .ap_continue( hls_threshold_Block_crit_edge_i_06_proc_U0_ap_continue ),
    .ap_idle( hls_threshold_Block_crit_edge_i_06_proc_U0_ap_idle ),
    .ap_ready( hls_threshold_Block_crit_edge_i_06_proc_U0_ap_ready ),
    .src_TDATA( hls_threshold_Block_crit_edge_i_06_proc_U0_src_TDATA ),
    .src_TVALID( hls_threshold_Block_crit_edge_i_06_proc_U0_src_TVALID ),
    .src_TREADY( hls_threshold_Block_crit_edge_i_06_proc_U0_src_TREADY ),
    .src_TKEEP( hls_threshold_Block_crit_edge_i_06_proc_U0_src_TKEEP ),
    .src_TSTRB( hls_threshold_Block_crit_edge_i_06_proc_U0_src_TSTRB ),
    .src_TUSER( hls_threshold_Block_crit_edge_i_06_proc_U0_src_TUSER ),
    .src_TLAST( hls_threshold_Block_crit_edge_i_06_proc_U0_src_TLAST ),
    .src_TID( hls_threshold_Block_crit_edge_i_06_proc_U0_src_TID ),
    .src_TDEST( hls_threshold_Block_crit_edge_i_06_proc_U0_src_TDEST ),
    .dst_TDATA( hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TDATA ),
    .dst_TVALID( hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TVALID ),
    .dst_TREADY( hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TREADY ),
    .dst_TKEEP( hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TKEEP ),
    .dst_TSTRB( hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TSTRB ),
    .dst_TUSER( hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TUSER ),
    .dst_TLAST( hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TLAST ),
    .dst_TID( hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TID ),
    .dst_TDEST( hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TDEST )
);



/// assign process. ///
always @(posedge ap_clk)
begin
    ap_CS <= ap_const_logic_0;
end

/// ap_sig_hs_done assign process. ///
always @ (hls_threshold_Block_crit_edge_i_06_proc_U0_ap_done)
begin
    if ((hls_threshold_Block_crit_edge_i_06_proc_U0_ap_done == ap_const_logic_1)) begin
        ap_sig_hs_done = ap_const_logic_1;
    end else begin
        ap_sig_hs_done = ap_const_logic_0;
    end
end

/// ap_rst_n_inv assign process. ///
always @ (ap_rst_n)
begin
    ap_rst_n_inv = ~ap_rst_n;
end
assign ap_sig_hs_continue = ap_const_logic_0;
assign dst_TDATA = hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TDATA;
assign dst_TDEST = hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TDEST;
assign dst_TID = hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TID;
assign dst_TKEEP = hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TKEEP;
assign dst_TLAST = hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TLAST;
assign dst_TSTRB = hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TSTRB;
assign dst_TUSER = hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TUSER;
assign dst_TVALID = hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TVALID;
assign hls_threshold_Block_crit_edge_i_06_proc_U0_ap_continue = ap_const_logic_1;
assign hls_threshold_Block_crit_edge_i_06_proc_U0_ap_start = ap_const_logic_1;
assign hls_threshold_Block_crit_edge_i_06_proc_U0_dst_TREADY = dst_TREADY;
assign hls_threshold_Block_crit_edge_i_06_proc_U0_src_TDATA = src_TDATA;
assign hls_threshold_Block_crit_edge_i_06_proc_U0_src_TDEST = src_TDEST;
assign hls_threshold_Block_crit_edge_i_06_proc_U0_src_TID = src_TID;
assign hls_threshold_Block_crit_edge_i_06_proc_U0_src_TKEEP = src_TKEEP;
assign hls_threshold_Block_crit_edge_i_06_proc_U0_src_TLAST = src_TLAST;
assign hls_threshold_Block_crit_edge_i_06_proc_U0_src_TSTRB = src_TSTRB;
assign hls_threshold_Block_crit_edge_i_06_proc_U0_src_TUSER = src_TUSER;
assign hls_threshold_Block_crit_edge_i_06_proc_U0_src_TVALID = src_TVALID;
assign src_TREADY = hls_threshold_Block_crit_edge_i_06_proc_U0_src_TREADY;


endmodule //hls_threshold

